### PR TITLE
Add `eigsolve_tol` as a keyword argument for the eigensolver

### PR DESCRIPTION
**Pull request by hershsingh**
This exposes the Krylov eigensolver tolerance `krylov_tol` as a keyword argument of the `vumps` function.

### CODE REVIEW

**Comment by mtfishman** [comment]
Looks good, thanks! I'll wait for tests to pass and then merge.

**Comment by hershsingh** [comment]
Looks like it failed the format test. Let me run JuliaFormatter on this.

**Comment by hershsingh** [comment]
I ran JuliaFormatter on the entire directory. Not sure why GitHub's check is failing on `src/infinitecanonicalmps.jl`

**Comment by mtfishman** [comment]
That's strange. I think I've seen that before, and the problem was that the Github CI workflow was using a different version of JuliaFormatter than I was using locally. I see that it is set to use Julia 1.3.0 here:
https://github.com/ITensor/ITensorInfiniteMPS.jl/blob/5b765f1a7a46939251e91f8c5233d0c7e1f4ad02/.github/workflows/format_check.yml#L16

You could try increasing that to Julia 1.7.1 and see if that helps. If that doesn't work than it's not worth spending time on, we can fix it later.

**Comment by hershsingh** [comment]
Ok, yes changing the version works. Thanks!

**Pull request merged**
